apiVersion: apps/v1
kind: Deployment
metadata:
  name: selec-backend-depl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector: 
    matchLabels:
      app: selec-backend
  template: 
    metadata:
      labels:
        app: selec-backend
    spec:
      containers:
        - name: selec-backend
          image: agamkashyap/review-portal-backend
          imagePullPolicy: Always
          ports:
            - name: apiport
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: selec-backend-svc
spec:
  type: LoadBalancer
  selector:
    app: selec-backend
  ports:
    - name: selec-backend
      protocol: TCP
      port: 3000
      targetPort: http