apiVersion: apps/v1
kind: Deployment
metadata:
  name: selec-frontend-depl
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector: 
    matchLabels:
      app: selec-frontend
  template: 
    metadata:
      labels:
        app: selec-frontend
    spec:
      containers:
        - name: selec-frontend
          image: keiserdocker/selec-frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: selec-frontend-svc
spec:
  type: NodePort
  selector:
    app: selec-frontend
  ports:
    - name: selec-frontend
      protocol: TCP
      port: 80
      targetPort: http